version: "3"

services:

  wordpress:
    image: as247/wp
    volumes:
      - {web_path}:/var/www/html
      - {db_path}:/var/lib/mysql
      - {php_ini_path}:/usr/local/etc/php/php.ini
    expose:
        - 80
    restart: always
    environment:
      VIRTUAL_HOST: {domain}
      MYSQL_ROOT_PASSWORD: g8nZDCFnxKvJSR
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: "hexience@12345"
      WORDPRESS_DB_HOST: 127.0.0.1
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: "hexience@12345"
      WORDPRESS_DB_NAME: wp
    container_name: {domain}

networks:
  default:
    external:
      name: nginx-proxy
